Update requirements.txt, except sphinx-related, to fix for python3.9
Regenerate requirements.txt from requirements.in using pip-compile (but
with sphinx's version fixed) to solve the following error on python 3.9:

Traceback (most recent call last):
  File "/home/nfraprado/cur/git/rst2pdf/env/bin/rst2pdf", line 5, in <module>
    from rst2pdf.createpdf import main
  File "/home/nfraprado/cur/git/rst2pdf/env/lib/python3.9/site-packages/rst2pdf/createpdf.py", line 65, in <module>
    from reportlab.platypus import doctemplate
  File "/home/nfraprado/cur/git/rst2pdf/env/lib/python3.9/site-packages/reportlab/platypus/__init__.py", line 7, in <module>
    from .flowables import *
  File "/home/nfraprado/cur/git/rst2pdf/env/lib/python3.9/site-packages/reportlab/platypus/flowables.py", line 29, in <module>
    from reportlab.lib.colors import red, gray, lightgrey
  File "/home/nfraprado/cur/git/rst2pdf/env/lib/python3.9/site-packages/reportlab/lib/colors.py", line 45, in <module>
    from reportlab.lib.utils import asNative, isStr, rl_safe_eval
  File "/home/nfraprado/cur/git/rst2pdf/env/lib/python3.9/site-packages/reportlab/lib/utils.py", line 10, in <module>
    from base64 import decodestring as base64_decodestring, encodestring as base64_encodestring
ImportError: cannot import name 'decodestring' from 'base64' (/usr/lib/python3.9/base64.py)

decodestring was removed in python3.9, and newer versions of reportlab
no longer rely on it, so update packages to fix it.

Sphinx, on the other hand, has had various changes, mainly regarding
code domains, so there will probably be code changes necessary to
correctly handle that and then update the related tests. So don't update
Sphinx for the time being.