Fix error with xhtml2pdf import
After updating xhtml2pdf, the following error happens:

Traceback (most recent call last):
  File "/home/nfraprado/cur/git/rst2pdf/env2/bin/rst2pdf", line 33, in <module>
    sys.exit(load_entry_point('rst2pdf', 'console_scripts', 'rst2pdf')())
  File "/home/nfraprado/cur/git/rst2pdf/env2/bin/rst2pdf", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/createpdf.py", line 105, in <module>
    from rst2pdf.nodehandlers import nodehandlers
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/nodehandlers.py", line 7, in <module>
    from . import genelements  # noqa
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/genelements.py", line 61, in <module>
    from .utils import parseRaw, parseHTML
  File "/home/nfraprado/cur/git/rst2pdf/rst2pdf/utils.py", line 85, in <module>
    from xhtml2pdf.util import COLOR_BY_NAME
  File "/home/nfraprado/cur/git/rst2pdf/env2/lib/python3.9/site-packages/xhtml2pdf/util.py", line 12, in <module>
    import xhtml2pdf.default
  File "/home/nfraprado/cur/git/rst2pdf/env2/lib/python3.9/site-packages/xhtml2pdf/default.py", line 611, in <module>
    DEFAULT_ASIAN_FONT = util.get_default_asian_font()
AttributeError: partially initialized module 'xhtml2pdf.util' has no attribute 'get_default_asian_font' (most likely due to a circular import)

Importing xhtml2pdf.default before the xhtml2pdf.util import solves it.
Though that makes flake8 complain:

rst2pdf/utils.py:85:5: F401 'xhtml2pdf.default' imported but unused

So also add #NOQA to that line to silence it.